My_Ecom_Project/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile')
]

My_Ecom_Project/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

My_Ecom_Project/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/',views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),
]

My_Ecom_Project/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/',views.ProductDetail.as_view(), name='product_detail')
]

My_Ecom_Project/My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('accounts/',include('App_Login.urls')),
    path('shop/',include('App_Order.urls')),
    path('paymemt/',include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Ecom_Project/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Ecommerce Project{% endblock title %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

   <style>
    .card{
      height: 350px;
    }
    .card-product:after{
     content: "";
     display: table;
     clear: both;
     visibility: hidden;
    }
    .card-product .price-new, .card-product .price{
      margin-right: 5px;
    }
    .card-product .price-old{
      color: #999;
    }
    .card-product .img-wrap{
      border-radius: 3px 3px 0 0;
      overflow: hidden;
      position: relative;
      height: 220px;
      text-align: center;
    }

    .card-product .img-wrap img{
      max-hidth: 100%;
      max-height: 100%;
      object-fit: cover;
    }
    .card-product .info-wrap{
       overflow: hidden;
       padding: 15px;
       border-top: 1px solid #eee;
    }
    .card-product .action-wrap{
      padding-top: 4px;
      margin-top: 4px;
    }

    .card-product .bottom wrap{
     padding: 15px;
     border-top: 1px solid #eee;
    }
    .card-product .title{
      margin-top: 0px;
      
    }



   </style>
       

  </head>
  <body>
    {% include 'navbar.html' %}

   
    <br>
    <div class="container" style="padding-top 20px;">
      <div class="messages container mt-2">
        
          {% if messages %}
          {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}} 
            alert-dismissible fade show"
                {% endif %} role="alert">
                {{message}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            
              <!--
                <button type="button" class="close" data-dismiss="alert" aria-level="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              -->
              
            </div>
          {% endfor %}
        {% endif %}
        
        
      </div>



      {% block body_block %}
      {% endblock body_block %}
    </div>
    


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

My_Ecom_Project/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}">Django Ecommerce Project</a>
        <button type="button" class="navbar-toggler" 
        data-toggle="collapse" data-target="#navbarNav"
         aria-controls="navbarNav" aria-expanded="false" 
         aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
        </button>
        
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Order:cart' %}">
                    <i class="bi bi-cart" style="font-size:24px;"
                     ></i>Cart
                    <span>({{ request.user | cart_total }})</span>
                </a>
                
            </li>
            <!--
                <div class="dropdown">
                <a class="btn btn-secondary dropdown-toggle" 
                href="#" role="button" id="dropdownMenuLink" 
                data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
              
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </div>
            -->
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" 
                    id="navbarDropdown" role="button" 
                    data-bs-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                 <i class="bi bi-person-circle"></i>{{request.user.profile.username}}
                </a>
                
                 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a>
                    <div class="dropdown-divider"> </div>
                    <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                 </div>
            </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'App_Login:login' %}" class="btn btn-info btn-sm">Login</a>
                    <a href="{% url 'App_Login:signup' %}" class="btn btn-info btn-sm">Signup</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>